# Copyright (C) 2018 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

logging:
  file.name: build/logs/application.log

  level:
    de.hska: TRACE
    io.github.resilience4j.utils.RxJava2OnClasspathCondition: WARN

    org:
      springframework:
        boot.devtools.autoconfigure.ConditionEvaluationDeltaLoggingListener: WARN
        cloud.netflix.core.CoreAutoConfiguration: ERROR
        http.codec.json.Jackson2JsonEncoder: DEBUG
        security.core:
          userdetails.User: ERROR
          # SpringSecurityCoreVersion: ERROR
        web.server.adapter.HttpWebHandlerAdapter: DEBUG
        # data.mongodb.core.MongoTemplate
        # cloud.sleuth

      mongodb.driver.cluster: WARN
      apache.kafka.clients.NetworkClient: ERROR
      hibernate.validator.internal.xml:
        ValidationXmlParser: WARN
        ValidationBootstrapParameters: WARN
      junit.jupiter.engine.descriptor.TestInstanceLifecycleUtils: WARN
